project:
  type: website

website:
  title: "Degrees of Freedom Project"
  navbar:
    logo: DOFPro_D7_Red_Flame_No_Background_cropped.png
    logo-alt: "DOFPro Logo"
    left:
      - text: 'Chemical and Thermal Processes'
        menu:
        - href: ChemE.qmd
          text: Intro
        - href: https://dofpro.org/CTP/
          text: Website
      - text: 'Rocketry'
        menu:
        - href: Rocketry.qmd
          text: Intro
        - href: https://dofpro.org/RCK/
          text: Website
      - href: samples.qmd
        text: Samples


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

execute:
  freeze: auto